# Generated by Django 6.0.3 on 2026-04-01 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='study_field',
            field=models.CharField(blank=True, choices=[('social', 'Social Sciences'), ('natural', 'Natural Sciences')], help_text='Required only for grade 11 and 12', max_length=10, null=True),
        ),
    ]
