# Generated by Django 6.0.3 on 2026-04-02 16:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
        ('uploads', '0005_upload_is_active_upload_source_type_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quiz',
            old_name='topic_name',
            new_name='topic_title',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='is_completed',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='total_questions',
        ),
        migrations.AlterField(
            model_name='quiz',
            name='score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='upload',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uploads.upload'),
        ),
        migrations.DeleteModel(
            name='QuizAttempt',
        ),
    ]
