# Generated by Django 6.0.3 on 2026-04-02 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_rename_topic_name_quiz_topic_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='quiz',
            name='total_questions',
            field=models.IntegerField(default=5),
        ),
    ]
