# Generated by Django 6.0.3 on 2026-04-02 20:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('studyroom', '0002_studysession_study_field'),
        ('uploads', '0005_upload_is_active_upload_source_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Summary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic_title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('key_terms', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='summaries', to='studyroom.studysession')),
                ('upload', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uploads.upload')),
            ],
        ),
    ]
