# Generated by Django 6.0.3 on 2026-04-01 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='field',
            field=models.CharField(blank=True, choices=[('social', 'Social Sciences'), ('natural', 'Natural Sciences')], help_text='Subjects for specific study fields; null = common subject', max_length=10, null=True),
        ),
    ]
