# Generated by Django 6.0.3 on 2026-04-01 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upload',
            name='file',
            field=models.FileField(upload_to='UserPDF/'),
        ),
        migrations.AlterField(
            model_name='upload',
            name='file_type',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
