# Generated by Django 6.0.3 on 2026-04-01 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0002_alter_upload_file_alter_upload_file_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upload',
            name='extracted_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
