# Generated by Django 6.0.3 on 2026-04-02 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0003_alter_upload_extracted_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='upload',
            name='is_valid_for_subject',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='upload',
            name='validation_feedback',
            field=models.TextField(blank=True, null=True),
        ),
    ]
