# Generated by Django 6.0.3 on 2026-04-02 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0004_upload_is_valid_for_subject_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='upload',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='upload',
            name='source_type',
            field=models.CharField(choices=[('system', 'System'), ('user', 'User')], default='user', max_length=10),
        ),
        migrations.AddField(
            model_name='upload',
            name='table_of_contents',
            field=models.TextField(blank=True, null=True),
        ),
    ]
