# Generated by Django 6.0.3 on 2026-04-01 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studyroom', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studysession',
            name='study_field',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
